version: '3'
services:
  pg_service:
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - blogger_store:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  blogger_store: